CREATE TYPE "status" AS ENUM ('Doing', 'Done', 'Inprocess', 'Deleted');
CREATE TABLE "task" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" VARCHAR(255) NOT NULL,
    "description" text,
    "image" json,
    "status" status,
    "created_at" TIMESTAMP DEFAULT (now()),
    "updated_at" TIMESTAMP DEFAULT (now())
);
CREATE TABLE "user" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_name" VARCHAR(50) NOT NULL,
    "hashed_password" VARCHAR(256) NOT NULL,
    "first_name" VARCHAR(50) NOT NULL,
    "last_name" VARCHAR(50) NOT NULL,
    "date_of_birth" TIMESTAMP NOT NULL,
    "email" VARCHAR(50) NOT NULL,
    "created_at" TIMESTAMP DEFAULT (now())
);
CREATE TABLE "assignment" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "task_id" INT,
    "user_id" INT,
    "created_at" TIMESTAMP DEFAULT (now())
);
CREATE INDEX "idx" ON "task" ("id");
CREATE INDEX "idx_username" ON "user" ("user_name");
ALTER TABLE "assignment"
ADD FOREIGN KEY ("task_id") REFERENCES "task" ("id");
ALTER TABLE "assignment"
ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");