// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: assignment.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAssignment = `-- name: GetAssignment :one
SELECT id, task_id, user_id, created_at
FROM assignment
WHERE task_id = $1
    AND user_id = $2
`

type GetAssignmentParams struct {
	TaskID pgtype.Int4
	UserID pgtype.Int4
}

func (q *Queries) GetAssignment(ctx context.Context, arg GetAssignmentParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, getAssignment, arg.TaskID, arg.UserID)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}
