// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Status string

const (
	StatusDoing     Status = "Doing"
	StatusDone      Status = "Done"
	StatusInprocess Status = "Inprocess"
	StatusDeleted   Status = "Deleted"
)

func (e *Status) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Status(s)
	case string:
		*e = Status(s)
	default:
		return fmt.Errorf("unsupported scan type for Status: %T", src)
	}
	return nil
}

type NullStatus struct {
	Status Status
	Valid  bool // Valid is true if Status is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatus) Scan(value interface{}) error {
	if value == nil {
		ns.Status, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Status.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Status), nil
}

type Assignment struct {
	ID        int32
	TaskID    pgtype.Int4
	UserID    pgtype.Int4
	CreatedAt pgtype.Timestamp
}

type Task struct {
	ID          int32
	Title       string
	Description pgtype.Text
	Image       []byte
	Status      NullStatus
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type User struct {
	ID             int32
	UserName       string
	HashedPassword string
	Salt           string
	FirstName      string
	LastName       string
	DateOfBirth    pgtype.Timestamp
	Email          string
}
