// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Status string

const (
	StatusDoing     Status = "Doing"
	StatusDone      Status = "Done"
	StatusInprocess Status = "Inprocess"
)

func (e *Status) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Status(s)
	case string:
		*e = Status(s)
	default:
		return fmt.Errorf("unsupported scan type for Status: %T", src)
	}
	return nil
}

type NullStatus struct {
	Status Status
	Valid  bool // Valid is true if Status is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatus) Scan(value interface{}) error {
	if value == nil {
		ns.Status, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Status.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Status), nil
}

type Assignment struct {
	ID        int32
	TaskID    sql.NullInt32
	UserID    sql.NullInt32
	CreatedAt sql.NullTime
}

type Task struct {
	ID          int32
	Title       string
	Description sql.NullString
	Image       pqtype.NullRawMessage
	Status      NullStatus
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type User struct {
	ID             int32
	UserName       string
	HashedPassword string
	Salt           string
	FirstName      string
	LastName       string
	DateOfBirth    time.Time
	Email          string
}
