// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"context"
)

type Querier interface {
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTask(ctx context.Context, id int32) (Task, error)
	DeleteUser(ctx context.Context, userName string) error
	GetAssignment(ctx context.Context, arg GetAssignmentParams) (Assignment, error)
	GetTask(ctx context.Context, id int32) (Task, error)
	GetUser(ctx context.Context, userName string) (User, error)
	ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error)
	UpdateStatus(ctx context.Context, arg UpdateStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
